name: 'CVE Binary Tool'
description: "CVE Binary Tool's official GitHub Action"
author: 'b31ngd3v'
branding:
  icon: 'shield'
  color: 'gray-dark'
inputs:
  nvd_api_key:
    required: false
    description: 'NVD API Key is required for downloading National Vulnerbility Database.'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: 'python3-pip'
    - run: pip install git+https://github.com/intel/cve-bin-tool@main reportlab
      shell: bash
    - run: >
        cve-bin-tool .
        --format html,pdf
        --output-file scan-result
        --nvd-api-key '${{ inputs.nvd_api_key }}'
        --use-mirror 'https://raw.githubusercontent.com/sec-data/mirror-sandbox/main'
        --verify "${GITHUB_ACTION_PATH}/public.key"
      continue-on-error: true
      shell: bash
    - run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/b31ngd3v/vulnerable-binaries/actions/artifacts/735640624/zip
      shell: bash
