name: 'CVE Binary Tool'
description: "CVE Binary Tool's official GitHub Action"
author: 'b31ngd3v'
branding:
  icon: 'shield'
  color: 'gray-dark'
inputs:
  nvd_api_key:
    required: false
    description: 'NVD API Key is required for downloading National Vulnerbility Database.'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: 'python3-pip'
    - run: pip install git+https://github.com/intel/cve-bin-tool@main reportlab
      shell: bash
    - run: >
        cve-bin-tool .
        --format html,pdf
        --output-file scan-result
        --nvd-api-key '${{ inputs.nvd_api_key }}'
        --use-mirror 'https://raw.githubusercontent.com/sec-data/mirror-sandbox/main'
        --verify "${GITHUB_ACTION_PATH}/public.key"
      continue-on-error: true
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: cve_reports
        path: |
          scan-result.html
          scan-result.pdf
        if-no-files-found: ignore
    - run: python3 "${GITHUB_ACTION_PATH}/src/generate-sarif.py" -r '${{ github.repository }}' -R '${{ github.run_id }}' -o "/tmp/scan-report.sarif" --reports-only
      shell: bash
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: /tmp/scan-report.sarif
        category: cve-bin-tool
