name: 'CVE Binary Tool'
description: "CVE Binary Tool's official GitHub Action"
author: 'b31ngd3v'
branding:
  icon: 'shield'
  color: 'gray-dark'
inputs:
  nvd_api_key:
    required: false
    description: 'NVD API Key is required for downloading National Vulnerbility Database.'
runs:
  using: 'composite'
  steps:
    - run: mv "${GITHUB_ACTION_PATH}/scan-report.sarif" .
      shell: bash
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: scan-report.sarif
        category: cve-bin-tool
